CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE meituan (
  meituan_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  phone varchar(64) NOT NULL,
  latest_week_coupou integer NOT NULL,
  city_id integer NOT NULL,
  addr varchar(256) NOT NULL,
  brand_name varchar(256) NOT NULL,
  brand_id integer NOT NULL,
  poi_id integer NOT NULL,
  group_info integer NOT NULL,
  show_type varchar(36) NOT NULL,
  is_snack boolean NOT NULL,
  discount varchar(64) NOT NULL,
  history_coupon_count integer NOT NULL,
  avg_price integer NOT NULL,
  avg_score real NOT NULL,
  lowest_price real NOT NULL,
  introduction text NOT NULL,
  mark_numbers integer NOT NULL,
  area_id integer NOT NULL,
  subway_station_id varchar(256) NOT NULL,
  preferent boolean NOT NULL,
  is_support_appointment boolean NOT NULL,
  reference_price integer NOT NULL,
  style text NOT NULL,
  feature_menus text NOT NULL,
  name varchar(256) NOT NULL,
  lng real NOT NULL,
  lat real NOT NULL,
  is_waimai boolean NOT NULL,
  is_hot boolean NOT NULL,
  mall_id integer NOT NULL,
  has_group boolean NOT NULL,
  cates varchar(256) NOT NULL,
  wifi boolean NOT NULL,
  allow_refund boolean NOT NULL,
  area_name varchar(64) NOT NULL,
  open_info varchar(256) NOT NULL,
  cate_name varchar(64) NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW(),
  updated_at timestamptz NOT NULL DEFAULT NOW(),
  PRIMARY KEY(meituan_id),
  UNIQUE(poi_id)
);